# Generated by Django 6.0 on 2026-01-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mno',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
