# Generated by Django 6.0 on 2026-01-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='uprofile',
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='customer', max_length=26),
        ),
    ]
