# Generated by Django 6.0 on 2026-01-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_profile_user_uprofile_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccategory', models.CharField(choices=[('residence', 'residence'), ('corporate', 'corporate')], max_length=30)),
                ('ptitle', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('summary', models.TextField()),
                ('pimage', models.ImageField(upload_to='interior')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
